version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./AspNetCoreOnDocker.sln && dotnet publish ./AspNetCoreOnDocker.sln -c Release -o ./obj/Docker/publish"
